spring:
  data:
    mongodb:
      username: ziadsalah
      password: ziadsalah
      host: localhost
      port: 27017
      database: Notification
      authentication-database: admin



  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:  org.apache.kafka.common.serialization.ByteArrayDeserializer
      #properties:
        #spring.json.trusted.packages: '*'
        #spring.json.type.mapping: paymentConfirmation:com.MicroserviceEC.ecomerce.Notification.Kafka.payment.PaymentConfirmation,orderConfirmation:com.MicroserviceEC.ecomerce.Notification.Kafka.order.OrderConfirmation

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


server:
  port :
    9090